name: Rust - Release
description: "Release new crate version"

runs:
  using: composite
  steps:
    - run: cargo build --release
      shell: bash

    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ github.ref_name }}
        files: target/release/*
        prerelease: ${{ contains(github.ref_name, '-rc') }}