name: Rust - Release
description: "Release new crate version"

runs:
  using: composite
  steps:
    - run: cargo build --release
      shell: bash

    - uses: softprops/action-gh-release@v1
      if: ${{ github.event.base_refs == 'refs/head/main' }}
      with:
        tag_name: ${{ github.ref_name }}
        files: target/release/*