name: Rust - Release
description: "Release new crate version"

runs:
  using: composite
  steps:
    - run: cargo build --release
      shell: bash

    - run: |
        mkdir -p release-assets
        find target/release -maxdepth 1 -type f -executable \
          ! -name "*.d" \
          ! -name "*.rlib" \
          -exec cp {} release-assets/ \;
      shell: bash

    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ github.ref_name }}
        files: release-assets/*
        prerelease: ${{ contains(github.ref_name, '-rc') }}