name: Rust Security

on:
  workflow_call:

jobs:
  rust-deny:
    runs-on:
      labels: komrad-runners
    steps:
      - uses: actions/checkout@v5
      - uses: komrad-company/Kontinuous-integration/.github/actions/rust/deny@main
  rust-geiger:
    runs-on:
      labels: komrad-runners
    container:
      image: rust:1.95
    steps:
      - uses: actions/checkout@v5
      - uses: komrad-company/Kontinuous-integration/.github/actions/rust/geiger@main

