name: Pipeline (gRPC)

on:
  workflow_call:

jobs:
  test:
    runs-on:
      labels: komrad-runners
    container:
      image: rust:1.95
    steps:
      - uses: actions/checkout@v6
      - uses: komrad-company/Kontinuous-integration/.github/actions/proto/setup@main
      - uses: komrad-company/Kontinuous-integration/.github/actions/rust/tests@main

  lint:
    runs-on:
      labels: komrad-runners
    container:
      image: rust:1.95
    steps:
      - uses: actions/checkout@v6
      - uses: komrad-company/Kontinuous-integration/.github/actions/proto/setup@main
      - uses: komrad-company/Kontinuous-integration/.github/actions/rust/fmt@main
        with:
          continue-on-error: false
      - uses: komrad-company/Kontinuous-integration/.github/actions/rust/clippy@main

  release:
    runs-on:
      labels: komrad-runners
    container:
      image: rust:1.95
    needs:
      - lint
      - test
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@v6
      - uses: komrad-company/Kontinuous-integration/.github/actions/proto/setup@main
      - uses: komrad-company/Kontinuous-integration/.github/actions/rust/release@main

