name: Pipeline

on:
  workflow_call:

jobs:
  rust-security: # TODO transform on action
    runs-on:
      labels: komrad-runners
    steps:
      - uses: actions/checkout@v5

      - uses: komrad-company/Kompile-Konquer/.github/actions/rust/deny@main


  build:
    needs:
      - rust-security
    runs-on:
      labels: komrad-runners
    steps:
      - uses: actions/checkout@v5

      - uses: komrad-company/Kompile-Konquer/.github/actions/rust/build@main

  test:
    needs: build
    runs-on:
      labels: komrad-runners
    steps:
      - uses: actions/checkout@v5

      - uses: komrad-company/Kompile-Konquer/.github/actions/rust/tests@main

  lint:
    needs: build
    runs-on:
      labels: komrad-runners
    steps:
      - uses: actions/checkout@v5

      - uses: komrad-company/Kompile-Konquer/.github/actions/rust/fmt@main
        with:
          continue-on-error: false

      - uses: komrad-company/Kompile-Konquer/.github/actions/rust/clippy@main

  release:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@v5
      - uses: komrad-company/Kompile-Konquer/.github/actions/rust/release@main
