name: Pipeline

on:
  workflow_call:

jobs:
  cargo-deny: # TODO transform on action
    runs-on:
      labels: komrad-runners
    name: cargo deny (licences + bans + advisories)

    steps:
      - uses: actions/checkout@v5
      - uses: EmbarkStudios/cargo-deny-action@v2

  build:
    runs-on:
      labels: komrad-runners
    steps:
      - uses: actions/checkout@v4

      - uses: komrad-company/Kompile-Konquer/.github/actions/rust/build@main

  test:
    needs: build
    runs-on:
      labels: komrad-runners
    steps:
      - uses: actions/checkout@v4

      - uses: komrad-company/Kompile-Konquer/.github/actions/rust/tests@main

  lint:
    needs: build
    runs-on:
      labels: komrad-runners
    steps:
      - uses: actions/checkout@v4

      - uses: komrad-company/Kompile-Konquer/.github/actions/rust/fmt@main
        with:
          continue-on-error: false

      - uses: komrad-company/Kompile-Konquer/.github/actions/rust/clippy@main

  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@v4
      - uses: komrad-company/Kompile-Konquer/.github/actions/rust/release@main
